### ISSUE TITLE
webdriver manager

### ISSUE THREAD

**Issue by peterzhenghj** [mherrmann/selenium-python-helium#111]
Hi mherrmann,
So glad to see automatic chromedriver  added in V3.2.0

Also I found another  good way to do this:
[https://github.com/SergeyPirogov/webdriver_manager](https://github.com/SergeyPirogov/webdriver_manager)

Thanks

**Comment by mherrmann** [comment]
That looks great too. I'll be happy to accept a PR that uses it to automatically fetch geckodriver.

**Comment by mherrmann** [comment]
Switched to webdriver_manager in release 3.2.4.
