### ISSUE TITLE
Sometimes click doesn't work

### ISSUE THREAD

**Issue by DingLarry** [mherrmann/selenium-python-helium#17]
Hello, 

I tried to use below code to click the second Courses on web page but some times it works fine, most of the time just throws me an error saying LookUpError.
`click(find_all(Text("Courses"))[1])`
I also tried to use `click(S(selector="//li[@data-report='courses']/a"))` but i got the same problem, the first time it works fine, but the rest times don't work. Anyone has any idea?

**Comment by mherrmann** [comment]
Why not just `click("Courses")`?

**Comment by mherrmann** [comment]
Or `click(Text("Courses", below="Some other text"))`?

The reason it doesn't work with `find_all` is that `find_all` is evaluated immediately, whereas `click("some Text")` waits up to 10 seconds for "some text" to appear.

**Comment by DingLarry** [comment]
because there are more than two "Courses" in the same webpage. I'm pretty sure the xpath finds the element well but just doesn't work also.

**Comment by mherrmann** [comment]
I got that. Helium's recommended way of distinguishing such ambiguous occurrences is via `below=`, `to_right_of=`, `to_left_of=` and `above=`. See [here](https://github.com/mherrmann/selenium-python-helium/blob/master/doc/Cheatsheet.md#finding-elements-relative-to-others).
