### ISSUE TITLE
Link is matching partial text

### ISSUE THREAD

**Issue by permster** [mherrmann/selenium-python-helium#21]
I'm doing a simple `click(Link("Algebra I", below="Biology"))` to click dropdown links.  There are two values in the dropdown that are similar.

Algebra I
Algebra I Elective

It keeps clicking the one with "Elective" in the text which is only a partial match.  This is not the expected behavior is it?

How can I have it do a full text match and not partial?  I've tried using xPath `"//*/ul/li/a[text()='Algebra I']"` but it seems to have difficulty finding this dropdown text for some reason.

**UPDATE:**  I found the following workaround.  Not ideal but it works.
```
links = find_all(S("//*/ul/li/a"))
    for link in links:
        if link.web_element.text == "Algebra I":
            # match found
            click(link.web_element)
            break
```

**Comment by mherrmann** [comment]
Thank you for sharing your workaround. Wouldn't the following be nicer? `click(Link("Algebra I", below="Biology", above="Algebra I Effective"))`

**Comment by permster** [comment]
The problem is I only have the two data points.  The current class being displayed and the one I want to click on.  During normal use I won't there's a course that will interfere.  I was just surprised to find `Link()` doing partial text matching instead of matching the entire link text.

**Comment by mherrmann** [comment]
I see. Helium's more lax matching works great in many, many situations. But I can see how here it is a disadvantage. `find_all` like you used it is a good solution then.

I'll close this issue.

**Comment by permster** [comment]
Running into this same issue in a table using the example code in the cheat sheet.
https://github.com/mherrmann/selenium-python-helium/blob/master/doc/Cheatsheet.md#finding-all-elements

I have table column names like "Assignment" and "Assignment Type".  It appears to be matching the incorrect column name due to the partial matching.

Sure would be nice if this was a config class option for full or partial text matching.

**Comment by mherrmann** [comment]
> Sure would be nice

PRs are happily accepted. In this case, it should however not be a global config option but rather an option on each element class. Maybe it could be made so `Text("foo")` does prefix-matching like it does now but `Text(re.compile("foo"))` only matches exact strings.
