### ISSUE TITLE
Check current URL

### ISSUE THREAD

**Issue by shlomiLan** [mherrmann/selenium-python-helium#26]
Hey,

Again great package.
Is there any way to get the current URL? I have a login page and if the user login successfully he is redirected and I want to test that is redirected to the right URL.

Thanks.

**Comment by mherrmann** [comment]
Helium is based on Selenium. The main types of object you interact with in Selenium are _WebDrivers_. To get the WebDriver from Helium, you can do:

    get_driver()

Then, a quick Google search for your question - "selenium python get current url" - will show you that to get the current URL, you can do `web_driver.current_url`. Putting this together, we get, in Helium:

    get_driver().current_url

So in the future, if you have similar questions, try googling for "Selenium Python <your question>".

Cheers,
M
