### ISSUE TITLE
Is it possible to get the pixel color at coordinates (x;y)?

### ISSUE THREAD

**Issue by Jars-of-jam-Scheduler** [mherrmann/selenium-python-helium#27]
Hi,

I need to know the color of a given pixel within a canvas with Selenium.

How to do it?

Thank you in advance!
Best regards,

**Comment by mherrmann** [comment]
> with Selenium

This issue tracker is about Helium.

**Comment by Jars-of-jam-Scheduler** [comment]
Sorry @mherrmann I wanted to say "Helium"
