### ISSUE TITLE
Is it possible to dynamically traverse the element in the dom tree and set the focus for specific element ? 

### ISSUE THREAD

**Issue by masterliuf** [mherrmann/selenium-python-helium#30]
I have the requirement to automatically traverse the html elements through the python scripts, then set the focus of the elements in turn, and trigger the key press event to access the corresponding URL of the element.  The Demo is [here](http://demo-534942307.cn-north-1.elb.amazonaws.com.cn/vistools/epg7/index.html). So i want to ensure this project whether satify my requirement , and look forward to your replay.

**Comment by mherrmann** [comment]
It's possible with the Selenium integration. Please google or ask on StackOverflow for [your question] + Selenium Python. This will give you results that speak about a _WebDriver_. You can get the WebDriver which Helium uses via `get_driver()`. So: If a search result says `driver.execute_script(...)`, instead use `get_driver().execute_script(...)`.

Generally, your question is out of scope for this issue tracker, which is about bugs and improvements for Helium. I'm closing this issue. Please ask further questions on StackOverflow.
