### ISSUE TITLE
Set chromedriver path in start_chrome

### ISSUE THREAD

**Issue by shalonwoodchl** [mherrmann/selenium-python-helium#31]
It would be nice if you could set the path to chromedriver in start_chrome, similar to the way you can pass options to it, for use in a container. (I spent most of the day yesterday trying to figure out why selenium can't find chromedriver even if it's in the path, and all I found was that it happens and people work around it, apparently.)

As far as I can tell, there's no way to pass the path in options, or am I missing something? One line is much better than seven lines to start chrome....

**Comment by mherrmann** [comment]
Another use case for this feature is that the Chrome version that ships with Helium may be outdated. In that case too it would be useful to be able to specify the ChromeDriver to be used.

However, I'm not sure an extra argument to `start_chrome(...)` would be best. Maybe it would be better if Helium would simply pick up any ChromeDriver on the `PATH` first. If none is found there, _then_ Helium could use its own copy.

**Comment by ostojicmilica** [comment]
I also have issues with this can you give me workaround for now? And yes I also think that it would be amazing if Helium could cimply pick up ChromeDriver

**Comment by mherrmann** [comment]
Helium 3.0.5 now picks up chrome-/geckodriver from your `PATH`.
