### ISSUE TITLE
How do u actually use set_driver and get_driver to use selenium cookies?

### ISSUE THREAD

**Issue by BananaDrum** [mherrmann/selenium-python-helium#44]

**Comment by BananaDrum** [comment]
ok i found it 👍 
path_to_extension = 'Your Extension Path'

chrome_options = Options()
chrome_options.add_argument('load-extension=' + path_to_extension)
chrome_options.add_argument("--user-data-dir=chrome-data")
driver = webdriver.Chrome('chromedriver.exe',options=chrome_options)
driver.get("https://www.youtube.com/")

**Comment by utmcontent** [comment]
Where to use selenium cookies?
