### ISSUE TITLE
How to start a Firefox instance with a specific user profile?

### ISSUE THREAD

**Issue by someshwaran1997** [mherrmann/selenium-python-helium#51]
Hi, 
I am trying to figure out how to start a Firefox instance with a specific user profile. From [command line](https://github.com/mherrmann/selenium-python-helium/issues?q=is%3Aissue+is%3Aopen) it is possible by running 
`firefox -P default-relase`

Similarly from [selenium](https://github.com/mherrmann/selenium-python-helium/issues?q=is%3Aissue+is%3Aopen) it is possible by running
``` python
profile = FirefoxProfile(<path\to\profile\>)
driver = Firefox(firefox_profile=profile)
```

Any idea on how to do the same with helium?

**Comment by mherrmann** [comment]
Take a Python script that starts Firefox via Selenium (not via Helium). Set the `FirefoxProfile` there. Then, use Helium's `set_driver(...)` function to make Helium use your Firefox WebDriver instance.

**Comment by someshwaran1997** [comment]
Thanks @mherrmann 
I found a solution. Here is what I did:

``` Python
from selenium.webdriver import FirefoxOptions, FirefoxProfile
from pathlib import Path
path_to_profile = Path(r"<Path\to\profile>")
firefox_profile = FirefoxProfile(profile_directory=path_to_profile)
firefox_options = FirefoxOptions()
firefox_options.profile = firefox_profile
app = start_firefox(options=firefox_options)
```
