### ISSUE TITLE
How to do multiple select?

### ISSUE THREAD

**Issue by someshwaran1997** [mherrmann/selenium-python-helium#52]
Hi,

I am trying to select more than one option from a multi select element. 
Right now, I've achieved this by writing a select command for each option like

``` Python
select(ComboBox('multi select element'), 'option 1')
select(ComboBox('multi select element'), 'option 2')
select(ComboBox('multi select element'), 'option 4')
```

Is there any better or easy way to do this?

**Comment by mherrmann** [comment]
You could save the `ComboBox` in a variable. Other than that, no I don't think there's a better way.
