### ISSUE TITLE
Doesn't support the new Chrome 91 stable version

### ISSUE THREAD

**Issue by bradli99** [mherrmann/selenium-python-helium#61]
Hi, Helium doesn't support the new chrome 91 only 89 and returns error saying that.

Can you please show me how to update the chromedriver inside helium so it can support Chrome browser version 91 (stable, not beta or unstable). Without specifying the chrome driver too.

Is there a way to change the chromedricer directly inside Helium's files, without adding anything to the code.

Thank you

**Comment by mherrmann** [comment]
You can put the `chromedriver` executable on your `PATH`.

**Comment by bradli99** [comment]
Yeah but it will require Selenium again and i will have to specify it with driver = webdriver.Chrome(executable_path='chromedriver')

But I want something directly like driver = start_chrome()

Please help if you can, thanks for the fast reply.

**Comment by mherrmann** [comment]
I'm sorry I don't have time to help beyond what I wrote above.

**Comment by bradli99** [comment]
Okay, thank you

**Comment by nhidy** [comment]
> Hi, Helium doesn't support the new chrome 91 only 89 and returns error saying that.
> 
> Can you please show me how to update the chromedriver inside helium so it can support Chrome browser version 91 (stable, not beta or unstable). Without specifying the chrome driver too.
> 
> Is there a way to change the chromedricer directly inside Helium's files, without adding anything to the code.
> 
> Thank you

Hi bradli99,

You can update `chromedriver.exe` follow path `helium/_impl/webdrivers` in helium.

**Comment by mherrmann** [comment]
@sahil1610 do you happen to have any news on this?

**Comment by dhiraz266** [comment]
> Hi, Helium doesn't support the new chrome 91 only 89 and returns error saying that.
> 
> Can you please show me how to update the chromedriver inside helium so it can support Chrome browser version 91 (stable, not beta or unstable). Without specifying the chrome driver too.
> 
> Is there a way to change the chromedricer directly inside Helium's files, without adding anything to the code.
> 
> Thank you

Also After updating Latest Version `chromedriver.exe` to `helium/_impl/webdrivers` doesn't work `start_chrome(headless=True)`

**Comment by lucianmarin** [comment]
I'm not sure if this is related, but setting `binary_location` for `chrome.exe` fixed the issue on Windows.

**Comment by songge8** [comment]
WebDriver is built in, so why not include Chrome as well as Pyppeteer? This way, there will be no version mismatches and no conflicts with the original Chrome installation
Translated from youdao 
@lucianmarin @mherrmann

**Comment by shanehh** [comment]
works for me
```
import helium as H
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager


with webdriver.Chrome(ChromeDriverManager().install()) as driver:
    H.set_driver(driver)
    H.go_to(url)
```

**Comment by nmgcfyxl** [comment]
```python
import os

import helium as hl
from helium._impl import is_windows, get_canonical_os_name, make_executable


class MxAPIImpl(hl.APIImpl):
    def _use_included_web_driver(self, driver_name):
        if is_windows():
            driver_name += '.exe'
        driver_path = os.path.join(
            os.path.dirname(__file__), 'webdrivers', get_canonical_os_name(),
            driver_name
        )
        print(driver_path)
        if not os.access(driver_path, os.X_OK):
            try:
                make_executable(driver_path)
            except Exception:
                raise RuntimeError(
                    "The webdrivers located at %s is not executable." % driver_path
                ) from None
        return driver_path


hl._API_IMPL = MxAPIImpl()
```
