### ISSUE TITLE
Support dropdown list

### ISSUE THREAD

**Issue by yoonghm** [mherrmann/selenium-python-helium#71]
Would it be possible to select or change dropdown list?

**Comment by mherrmann** [comment]
You can use https://selenium-python-helium.readthedocs.io/en/latest/api.html#helium.select. But often, dropdowns in HTML are scripted with non-standard elements. In this case, you will need to use consecutive `click(...)`s and maybe some `write(...)`s.

**Comment by yoonghm** [comment]
Thank you @mherrmann for the tips.
