### ISSUE TITLE
hope to learn the code that is deleted IE and Java section.

### ISSUE THREAD

**Issue by iamxiaojianzheng** [mherrmann/selenium-python-helium#72]
Hi Mherrmann, I am a Java developer who has been researching how to automatically manage Frame and Windows to avoid frequent switching between elements. I'm honored to see your Helium. I think it's great. It fits my mind. Unfortunately, I still have some difficulty in reading python source code. I wonder if you can open source your previous Java code and provide it for everyone to learn. Thank you very much

**Comment by mherrmann** [comment]
Hi, the Java code is still here in the history of this repository. See for example: https://github.com/mherrmann/selenium-python-helium/tree/a7d55bdc81737c9fa8ce33ecf00319a76fdbc6c1

**Comment by iamxiaojianzheng** [comment]
> Hi, the Java code is still here in the history of this repository. See for example: https://github.com/mherrmann/selenium-python-helium/tree/a7d55bdc81737c9fa8ce33ecf00319a76fdbc6c1

Thankfully
